[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
coap = "0.14"
coap-lite = "0.11.3"
tokio = {version = "^1.32", features = ["full"]}
lazy_static = "1.4.0"
serde_json = "1.0"