[package]
name = "broker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coap = "0.14"
coap-lite = "0.11.3"
tokio = {version = "^1.32", features = ["full"]}
