[package]
name = "coap_pubsub"
version = "0.1.0"
authors = []
description = ""
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
coap = "0.14"
coap-lite = "0.11.3"
tokio = { version = "^1", features = ["full"] } 
serde_json = "1.0"
